<?php

namespace Braceyourself\EloquentVueTable;


use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;

class EloquentVueTableProvider extends ServiceProvider
{
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        $this->app->register(EloquentVueTableRouteProvider::class);
        $this->publishes([
            __DIR__.'/resources/js/' => resource_path('/js/components/braceyourself'),
        ],'public');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }


}
